//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gds.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_SPLASH                      102
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    103
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 104
#define CG_IDD_PROGRESS                 105
#define CG_IDS_PROGRESS_CAPTION         106
#define IDR_MAINFRAME                   128
#define IDR_GDSTYPE                     129
#define IDD_LAYER_DLG                   133
#define IDD_STRUCTURE_DLG               134
#define IDD_FILL_LIMIT_DLG              135
#define IDD_SHRINK_DLG                  136
#define IDD_LAYER_COLOR_DLG             137
#define IDD_FONTSIZE_DLG                138
#define IDC_CURSOR_ZOOM_UP              139
#define IDC_CURSOR_ZOOM                 140
#define IDC_CURSOR_ZOOM_DOWN            141
#define IDD_ANGLE_DLG                   142
#define IDD_GRID_DLG                    143
#define IDR_TOOLBAR                     148
#define IDR_MAINFRAME_ORG               149
#define IDD_FILL_PAT_DLG                152
#define IDD_STR_LEVEL_DLG               153
#define IDB_LOGO                        154
#define IDD_ABOUTBOX_ON                 156
#define IDB_SOLID                       157
#define IDB_FRAME                       158
#define IDB_XDIAG                       159
#define IDB_FDIAG                       160
#define IDB_RDIAG                       161
#define IDB_XHATCH                      162
#define IDB_HHATCH                      163
#define IDB_VHATCH                      164
#define IDB_HZIGZAG                     165
#define IDB_VZIGZAG                     166
#define IDB_PENPATTERN                  167
#define IDB_DUMMY                       168
#define IDD_MOVE_TO                     169
#define IDB_VWAVE                       171
#define IDB_HWAVE                       172
#define IDD_MEMO_DLG                    173
#define IDB_DUMMY_STRUCTURE             174
#define IDD_STRUCTURE_INFO              175
#define IDI_ICON_STRUCTURE_INFO         176
#define IDR_MENU_STRUCTURE              177
#define IDD_STOP_BUTTON                 179
#define IDD_LAYER_ORDER                 183
#define IDD_PRINT_SCALE_DLG             184
#define IDB_HDASH                       186
#define IDB_VDASH                       187
#define IDB_LIGHT                       188
#define IDB_FDIAG_DASH                  189
#define IDB_RDIAG_DASH                  190
#define IDB_DIA                         192
#define IDD_TIME_STAMP_DLG              193
#define IDD_TEXT_DUMP                   194
#define IDI_ICON_DUMP                   195
#define IDR_MENU_TEXT_DUMP              196
#define IDD_DEFAULT_TEC_DLG             197
#define IDD_ZIPSEL_DIALOG               198
#define IDD_AREA_DLG                    199
#define IDD_VIEW_SET_COMMENT            200
#define IDD_VIEW_SELECT                 201
#define CG_IDC_PROGDLG_PROGRESS         1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_SPIN                        1024
#define IDC_CHECK_OVERWRITE             1024
#define IDC_ALL_ON                      1033
#define IDC_ALL_OFF                     1034
#define IDC_STR_TREE                    1036
#define IDC_SHOW_ALL                    1037
#define IDC_LOAD_LAYER                  1037
#define IDC_HIDE_ALL                    1038
#define IDC_HATCH_LIMIT                 1038
#define IDC_SAVE_LAYER                  1038
#define IDC_UPDOWN_HATCH                1039
#define IDC_SHRINK_RATE                 1040
#define IDC_UPDOWN_DRAW                 1040
#define IDC_UPDOWN_RATE                 1041
#define IDC_DRAW_LIMIT                  1041
#define IDC_SPIN1                       1042
#define IDC_STR1                        1043
#define IDC_FONT_SIZE                   1044
#define IDC_VIEW_ANGLE                  1046
#define IDC_UPDOWN_ANGLE                1047
#define IDC_STRUCTURE                   1048
#define IDC_STR_LEVEL                   1053
#define IDC_UPDOWN_LEVEL                1054
#define IDC_XDIAG                       1056
#define IDC_FRAME                       1057
#define IDC_XHATCH                      1058
#define IDC_FDIAG                       1059
#define IDC_RDIAG                       1060
#define IDC_SOLID                       1061
#define IDC_HHATCH                      1062
#define IDC_VHATCH                      1063
#define IDC_HZIGZAG                     1064
#define IDC_VZIGZAG                     1065
#define IDC_HDASH                       1066
#define IDC_SUB_LEVEL                   1067
#define IDC_VWAVE                       1067
#define ID_APPLY                        1068
#define IDC_HWAVE                       1068
#define IDC_COORD_Y                     1069
#define IDC_VDASH                       1069
#define IDC_COORD_X                     1070
#define IDC_LIGHT                       1070
#define IDC_FB_CURSOR                   1071
#define IDC_FDIAG_DASH                  1071
#define IDC_VERSION_STRING              1072
#define IDC_RDIAG_DASH                  1072
#define IDC_DIA                         1073
#define IDC_CHECK_GRID                  1074
#define IDC_EDIT_SNAP_X                 1076
#define IDC_EDIT_SNAP_Y                 1078
#define IDC_GRDI_SIZE                   1080
#define IDC_RADIO_FREE                  1081
#define IDC_RADIO_DIAGONAL              1082
#define IDC_RADIO_XY                    1083
#define IDC_EDIT_SNAP_X2                1084
#define IDC_EDIT_MINOR_X                1084
#define IDC_EDIT_SNAP_X3                1085
#define IDC_EDIT_MINOR_Y                1085
#define IDC_EDIT_TEC_FILE_NAME          1085
#define IDC_EDIT_SNAP_X4                1086
#define IDC_EDIT_MAJOR_X                1086
#define IDC_EDIT_SNAP_X5                1087
#define IDC_EDIT_MAJOR_Y                1087
#define IDC_RADIO_GRID_DOT              1088
#define IDC_RADIO_GRID_LINE             1089
#define IDC_RADIO_GRID_NONE             1090
#define IDC_EDIT_MEMO                   1092
#define IDC_BUTTON_FONT                 1093
#define IDC_CHECK_OMIT_STRUCTURE        1094
#define IDC_RICHEDIT_STRUCTURE_INFO     1095
#define IDC_SCROLL_LAYER                1106
#define IDC_REORDER_LAYER               1109
#define IDC_LAYER_LIST                  1111
#define IDC_RADIO_WYSIWYG               1112
#define IDC_RADIO_FULL                  1113
#define IDC_EDIT_RATIO                  1114
#define IDC_SPIN_RATIO                  1115
#define IDC_BUTTON_AUTO                 1116
#define IDC_RADIO_VIEW_AREA             1117
#define IDC_RADIO_SCALING               1118
#define IDC_EDIT_RATIO_AREA             1119
#define IDC_SPIN_RATIO_AREA             1120
#define IDC_BUTTON_AUTO_AREA            1121
#define IDC_SPIN_PENWIDTH               1122
#define IDC_SLIDER_DENSITY              1123
#define IDC_SPIN_LEG_SIZE               1123
#define IDC_CHECK_HATCH_HD              1124
#define IDC_SPIN_HATCHPENWIDTH          1124
#define IDC_CHECK_SHRINK                1125
#define IDC_CHECK_LEGEND                1126
#define IDC_EDIT_LINE_WIDTH             1127
#define IDC_EDIT_SHRINK                 1128
#define IDC_CHECK_SCALE                 1129
#define IDC_CHECK_FOOTER                1130
#define IDC_COMBO_PEN_COLOR             1131
#define IDC_EDIT_LEG_SIZE               1132
#define IDC_EDIT_CREATION_DATE          1132
#define IDC_COMBO_LEG_LOC               1133
#define IDC_EDIT_ACCESS_DATE            1133
#define IDC_BUTTON_DUMP_HIERARCHY       1133
#define IDC_EDIT_HATCH_PEN_WIDTH        1134
#define IDC_EDIT_DUMP                   1134
#define IDC_EDIT_DB_NAME                1134
#define IDC_EDIT_HATCH_SPACING          1135
#define IDC_EDIT_FILE                   1135
#define IDC_SPIN_HATCHSPACING           1136
#define IDC_BUTTON_BROWSE               1136
#define IDC_BUTTON_CLEAR                1137
#define IDC_LIST_FILE                   1137
#define IDC_EDIT_LEFT                   1138
#define IDC_EDIT_TOP                    1139
#define IDC_RADIO_AREA                  1140
#define IDC_EDIT_RIGHT                  1142
#define IDC_EDIT_BOTTOM                 1143
#define IDC_LIST_FONTS                  1143
#define IDC_EDIT_CENTER_Y               1144
#define IDC_CHECK_BOLD                  1144
#define IDC_EDIT_CENTER_X               1145
#define IDC_CHECK_ITALIC                1145
#define IDC_EDIT_VIEW_COMMENT           1145
#define IDC_EDIT_RADIUS                 1146
#define IDC_VIEW_LIST                   1146
#define IDC_DELETE_VIEW                 1147
#define IDC_RADIO_CENTER                1148
#define IDC_EDIT_VIEW                   1148
#define IDC_SELECT_VIEW                 1149
#define IDC_VIEW_LIST_X                 1150
#define IDC_VIEW_LIST_Y                 1151
#define IDC_SCROLL_VIEW_LIST            1152
#define IDC_CLEAR_VIEWS                 1153
#define IDC_CHECK_HIDE_NONEXIST         1154
#define IDC_CHECK_SAVE_NONEXIST         1155
#define IDC_NUM_LAYER                   1156
#define IDC_LAYER_APPLY                 1157
#define IDC_EDIT_LAYER_NAME             1159
#define ID_CLOSE_LAYER_SETUP            1160
#define IDC_CHECK_USE_COLOR             1161
#define ID_SET_LAYER                    32771
#define ID_SELECT_STR                   32772
#define ID_HATCH_SWITCH                 32773
#define ID_SET_HATCH_LIMIT              32774
#define ID_ZOOM_UP                      32775
#define ID_ZOOM_DOWN                    32776
#define ID_FILL_SWITCH                  32777
#define ID_BK_COLOR_BLACK               32778
#define ID_BK_COLOR_WHITE               32779
#define ID_SET_SHRINK_RATE              32780
#define ID_INCREASE_FONT_SIZE           32782
#define ID_DECREASE_FONT_SIZE           32783
#define ID_SET_FONT_SIZE                32784
#define ID_VIEW_TEXT                    32786
#define ID_SHOW_STR_BOUNDARY            32787
#define ID_FIT_WINDOW                   32788
#define ID_SET_ANGLE                    32789
#define ID_MIRROR_X                     32791
#define ID_MIRROR_Y                     32792
#define ID_FILL                         32794
#define ID_HATCH_CROSS_DIAGONAL         32795
#define ID_HATCH_FORWARD_DIAGONAL       32796
#define ID_HATCH_REVERSE_DIAGONAL       32797
#define ID_HATCH_VERTICAL               32798
#define ID_HATCH_HORIZONTAL             32799
#define ID_HATCH_CROSS                  32800
#define ID_FILL_SOLID                   32801
#define ID_SHOW_CENTER_CROSS            32802
#define ID_SHOW_GRIDDLG                 32803
#define ID_REDRAW                       32804
#define ID_BUTTON_STRUCTURE             32806
#define ID_STRUCTURE_CB                 32831
#define ID_FILL_NONE                    32837
#define ID_WRITE_TO_EMF                 32838
#define ID_WRITE_PART_TO_EMF            32842
#define ID_STR_LEVEL_CB                 32843
#define ID_STRUCTURE_LEVEL              32844
#define ID_SCROLL_RIGHT                 32846
#define ID_SCROLL_LEFT                  32847
#define ID_SCROLL_UP                    32848
#define ID_SCROLL_DOWN                  32849
#define ID_MOUSE_CROSS                  32850
#define ID_CROWW_WINDOW                 32851
#define ID_MOUSE_CROSS_WINDOW           32852
#define ID_MOUSE_STANDARD               32853
#define ID_DRAW_SMALL                   32854
#define ID_SET_CURSOR_TO                32855
#define ID_SHOW_SPLASH_SCREEN           32858
#define ID_ZOOM_SWITCH                  32860
#define ID_OPEN_TECHNOLOGY_MAP          32862
#define ID_SAVE_TECHNOLOGY_MAP          32863
#define ID_SHOW_GRID                    32864
#define ID_GRID_LINE                    32865
#define ID_GRID_DOT                     32866
#define ID_MEASURE_SWITCH               32867
#define ID_DELETE_SCALE                 32868
#define ID_CYCLE_DIRECTION              32869
#define ID_MEMO_SWITCH                  32870
#define ID_DELETE_MEMO                  32871
#define ID_BACKGROUND_BLACK             32872
#define ID_BACKGROUND_WHITE             32873
#define ID_MOUSE_PLUS_WINDOW            32875
#define ID_SHOW_AREF                    32876
#define ID_AXIS_NONE                    32877
#define ID_AXIS_STRUCTURE_ORIGIN        32878
#define ID_AXIS_WINDOW_CENTER           32879
#define ID_SKELTON                      32881
#define ID_BUTTON_BACK                  32883
#define ID_STRUCTURE_INFO               32884
#define ID_CHANGE_STRUCTURE             32885
#define ID_FORCE_SKELTON_ON             32886
#define ID_FORCE_SKELTON_OFF            32887
#define ID_SELECT_ALL_CELL              32889
#define ID_BUTTON_STOP_DRAW             32890
#define ID_ZOOM_SWITCH_BY_KEY           32892
#define ID_MEMO_SWITCH_BY_KEY           32893
#define ID_MEASURE_SWITCH_BY_KEY        32894
#define ID_DELETE_ALL_MEMO              32895
#define ID_DELETE_ALL_RULER             32896
#define ID_STOP_DRAW                    32897
#define ID_END_RENDER                   32898
#define ID_DRAW_BY_LAYER                32900
#define ID_OVERWRITE_MODE               32901
#define ID_OUTLINE_PATH                 32902
#define ID_EXPAND_CELL                  32903
#define ID_PAN_TO                       32904
#define ID_HATCH_EXACT                  32905
#define ID_RULER_COLOR                  32906
#define ID_COLOR_MEMO                   32907
#define ID_SHOW_TIME_STAMP              32908
#define ID_LAYER_SETUP_AT_BOOT          32910
#define ID_SAVE_TEXT_DUMP               32912
#define ID_AUTO_REDRAW                  32913
#define ID_FORCE_REDRAW                 -32622
#define ID_DEBUG_SW_AREF_AREA           32916
#define ID_ZOOM_AREA                    32917
#define ID_SHOW_SPOT_ELEMENT            32918
#define ID_SHOW_BOUNDARY                32924
#define ID_SHOW_PATH                    32925
#define ID_VIEW_STORE                   32927
#define ID_VIEW_BACK                    32928
#define ID_SYNC_VIEW                    32929
#define ID_SYNC_VIEW_ALWAYS             32930
#define ID_FILE_OPEN_SAME_TEC           32931
#define ID_CLIP_POLYGON                 32932
#define ID_STATUSBAR                    63000
#define ID_SB_DRAW_TIME                 63003
#define ID_CYCLE_GRID                   63005
#define ID_SB_CMD_MESSAGE               63006
#define IDS_CANNOT_RUN_ON_16BIT_WINDOWS_LT_4 63007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32933
#define _APS_NEXT_CONTROL_VALUE         1162
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
